### ISSUE TITLE
Feature request: consider adding a license

### ISSUE THREAD

**Issue by almndbtr** [ourzora/mint-page-template#10]
## Summary

 Hi @ourzora! Would you be open to adding a license to this project? 💭

Without one, [this project is under exclusive copyright by default](https://choosealicense.com/no-permission/) and unless otherwise specified, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including the @ourzora team. 😅

(I realize I jumped the gun by cutting the earlier PR 😳 -- sorry about that 🙇‍♂️)

I humbly suggest the [MIT License](https://choosealicense.com/licenses/mit/#suggest-this-license) or GNU GPL v3.0 (like [what's done for ourzora/v3](https://github.com/ourzora/v3/blob/main/LICENSE)) as an option. 

If you're up for it and know which one you'd like, I wouldn't mind cutting a PR for it too! ✌️

**Comment by almndbtr** [comment]
cc: @kolber for the heads-up, as (I think) the primary contributor/maintainer of this repo 🙇‍♂️

**Comment by kolber** [comment]
Thanks for the reminder! LICENSE added (MIT). 🙇
