### ISSUE TITLE
Which repository does `@zoralabs/zord` live in?

### ISSUE THREAD

**Issue by almndbtr** [ourzora/mint-page-template#11]
👋 @ourzora! 

I noticed that [`@zoralabs/zord`](https://github.com/ourzora/mint-page-template/blob/be18936163f5f215cf7ef74b0730b4dd76553351/package.json#L24) is the underlying design system powering this project. I checked NPM and see that [it's publicly available and installable](https://www.npmjs.com/package/@zoralabs/zord), but I couldn't find where this might live on GitHub or another source code hosting site.

Keen to get the team's advice around which repository it might live in, and if it's open to the general public to use for personal or production use! 💭

**Comment by kolber** [comment]
Yes! Zord repo coming very soon. It is already MIT licensed, so please feel free to use it however you like :)
We're just sorting out the documentation / examples before we officially move it public I believe.

**Comment by almndbtr** [comment]
@kolber Ah, wonderful! I'll keep my eyes peeled for when it goes live.

Happy to test things out and contribute to it!

Closing ✌️

**Comment by almndbtr** [comment]
> We're just sorting out the documentation / examples 

For posterity! I discovered [Nouns Market](https://noun.market), which has a [Docs](https://noun.market/docs) section with a `Zord` tab for getting started with the Zora Design System. 🤩
