### ISSUE TITLE
Trouble deploying via Vercel

### ISSUE THREAD

**Issue by imlevelhead** [ourzora/mint-page-template#13]
<img width="863" alt="Screen Shot 2022-09-16 at 3 43 39 PM" src="https://user-images.githubusercontent.com/48930274/190827367-251fd7a4-587e-4bbb-9854-1ac316b5d1ae.png">
Recieved error 

> error An unexpected error occurred: "https://registry.yarnpkg.com/@zoralabs/zord/-/zord-1.0.1.tgz: Request failed \"404 Not Found\"".

- I added the correct Alchemy API key for `ALCHEMY_ID`
- `NEXT_PUBLIC_CHAIN_ID` 5
- `NEXT_PUBLIC_CONTRACT_ADDRESSES` 0xdEB17609296e9C7aDe179dD9e69D831eDAE7e14D

lmk if I messed up :)

**Comment by kolber** [comment]
Thanks for reporting @imlevelhead! It looks like an issue with one of the packages we're using. 
Let us look into it and get back to you.

**Comment by kolber** [comment]
This should be all fixed now @imlevelhead. We had a bit of an error with our NPM deployment setup, which should be all addressed now. Thanks for letting us know!

**Comment by imlevelhead** [comment]
Awesome, works great now 🙂
